apiVersion: v2
name: kubedns-shepherd
description: |
  A Kubernetes controller that manages the DNS configuration of workloads,
  ensuring efficient and reliable way to configure DNS within your Kubernetes cluster.
type: application

version: 0.4.4-rc.2
appVersion: "0.4.4-rc.2"

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder
