apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-metric-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: kubedns-shepherd
  {{- include "chart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    control-plane: controller-manager
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
