{{- if and .Values.prometheus.enabled .Values.prometheus.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: kubedns-shepherd
    service: metrics-service
  {{- include "chart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    control-plane: controller-manager
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.prometheus.port }}
    protocol: TCP
    targetPort: metrics
{{- end }}
