apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "chart.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.certmanager.enabled }}
    helm.sh/hook: post-install,post-upgrade
  {{- else }}
    helm.sh/hook: pre-install,pre-upgrade
  {{- end }}
    helm.sh/hook-weight: "1"
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  selfSigned: {}
