apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "chart.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "chart.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc'
  - '{{ include "chart.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: {{ include "chart.fullname" . }}-selfsigned-issuer
  secretName: {{ include "chart.fullname" . }}-webhook-server-cert
