{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    {{- if .Values.certManager.enabled }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kubedns-shepherd.resourceName" (dict "suffix" "serving-cert" "context" $) }}
    {{- end }}
  name: {{ include "kubedns-shepherd.resourceName" (dict "suffix" "validating-webhook-configuration" "context" $) }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "kubedns-shepherd.resourceName" (dict "suffix" "webhook-service" "context" $) }}
      namespace: {{ .Release.Namespace }}
      path: /validate-config-kubedns-shepherd-io-v1alpha1-dnsclass
  failurePolicy: Fail
  name: vdnsclass.kubedns-shepherd.io
  rules:
  - apiGroups:
    - config.kubedns-shepherd.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dnsclasses
  sideEffects: None
{{- end }}
