# permissions for end users to edit dnsclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dnsclass-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubedns-shepherd
    app.kubernetes.io/part-of: kubedns-shepherd
    app.kubernetes.io/managed-by: kustomize
  name: dnsclass-editor-role
rules:
- apiGroups:
  - config.kubedns-shepherd.io
  resources:
  - dnsclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.kubedns-shepherd.io
  resources:
  - dnsclasses/status
  verbs:
  - get
