apiVersion: config.kubedns-shepherd.io/v1alpha1
kind: DNSClass
metadata:
  labels:
    app.kubernetes.io/name: dnsclass
    app.kubernetes.io/instance: dnsclass-without-nameserver-sample
    app.kubernetes.io/part-of: kubedns-shepherd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubedns-shepherd
  name: dnsclass-without-nameserver-sample
spec:
  allowedNamespaces:
    - default
  dnsConfig:
    searches:
      - "svc.{{ .clusterDomain }}"
      - "{{ .podNamespace }}.svc.{{ .clusterDomain }}"
    options:
      - name: ndots
        value: "2"
      - name: edns0 
