apiVersion: config.kubedns-shepherd.io/v1alpha1
kind: DNSClass
metadata:
  labels:
    app.kubernetes.io/name: dnsclass
    app.kubernetes.io/instance: dnsclass-sample
    app.kubernetes.io/part-of: kubedns-shepherd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubedns-shepherd
  name: dnsclass-all-namespaces-sample
spec:
  # If set, this flag disables dynamic DNS configuration for pods. This feature is not disabled by default,
  # any changes to DNSClass configuration or the addition of a new DNSClass will trigger a restart of
  # all pods affected by these changes to apply the new DNS configuration.
  disablePodRestart: false
  disabledNamespaces:
  - kube-system
  allowedDNSPolicies:
  - None
  - ClusterFirst
  - ClusterFirstWithHostNet
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 10.96.0.10
    searches:
      - svc.cluster.local
    options:
      - name: ndots
        value: "2"
      - name: edns0 
