apiVersion: config.kubedns-shepherd.io/v1alpha1
kind: DNSClass
metadata:
  labels:
    app.kubernetes.io/name: dnsclass
    app.kubernetes.io/instance: dnsclass-sample
    app.kubernetes.io/part-of: kubedns-shepherd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubedns-shepherd
  name: dnsclass-without-nameserver-sample
spec:
  allowedNamespaces:
    - default
  # If set, any changes to DNSClass configuration or the addition of a new DNSClass
  # will trigger a restart for all matched pods to apply the new DNS configuration.
  # This feature is disabled by default.
  enablePodRestart: true
  dnsConfig:
    searches:
      - svc.cluster.local
    options:
      - name: ndots
        value: "2"
      - name: edns0 
