name: Unit test

permissions:
  contents: read

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yaml'
      - 'chart/**'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yaml'
      - 'chart/**'
      - 'LICENSE'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Perform the test
        run: make test
      - name: Upload cover.out
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: cover.out
      - name: Report failure
        uses: nashmaniac/create-issue-action@v1.2
        # Only report failures of pushes (PRs have are visible through the Checks section) to the default branch
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          title: 🐛 Unit tests failed for ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: kind/bug
          body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

  coverage:
    name: Code coverage
    needs:
      - test
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Download cover.out
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
      - name: Send the coverage output
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out
